services:
  mydonut:
    container_name: mydonut
    environment:
      - TZ=Asia/Seoul
    ports:
      - 52222:22
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/mydonut
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ipc: host  # 공유 메모리 설정 추가
